pipeline:
  build:
    image: docker
    volume:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t biniam/example-webserver .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run biniam/example-webserver /test.sh

  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u biniam -p $PASS
      - docker push biniam/example-webserver
      
  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull biniam/example-webserver
      - docker stack deploy -c ./docker-compose.yml example-webs
