pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t biniam/example-webserver:$DRONE_COMMIT_SHA .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run biniam/example-webserver:$DRONE_COMMIT_SHA /test.sh

  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u biniam -p $PASS
      - docker push biniam/example-webserver:$DRONE_COMMIT_SHA
      
  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull biniam/example-webserver:$DRONE_COMMIT_SHA
      - docker tag biniam/example-webserver:$DRONE_COMMIT_SHA biniam/example-webserver:latest
      - docker stack deploy -c ./docker-compose.yml example-webserver
